[package]
name = "paco"
version = "0.1.0"
authors = ["Matthias Nilsson <matthias.nilsson@kb.se>"]

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
csv = "1.0.0-beta.4"
serde = "1.0.12"
serde_derive = "1.0.12"

